### ISSUE TITLE
咨询该项目

### ISSUE THREAD

**Issue by sse8-dev** [lgnyy/wrieguard-p2p#1]
你好，能稍微详细说明一下该项目如何使用吗？最小几台机器测试，可以在NAT后使用吗？

**Comment by lgnyy** [comment]
至少2台客户端机器，可以在NAT后使用；但不要在4G网络上用（无法建立p2p），比如手机开热点。
已经修改readme（增加例子说明）。

**Comment by sse8-dev** [comment]
谢谢及时回复。
还是不太明白过程。我这边按照你提供的指令测试，主要有两个问题：
1、各个命令没有啥输出信息提示，从而也就无法知道程序当前具体收到了什么内容，也就不知道每一条指令输入后，到底会有啥作用。
2、管理指令输入后，会进入死循环？我这边无法靠按下CTRL+C终止程序运行。

**Comment by lgnyy** [comment]
## 3个进程都有日志输出，重点看转发服务的日志，过程如下：
1. client发出请求给中转服务
2. wgtrf收到请求后，转发给对端
3. 对端wgsvr收到后，修改wireguard的peer信息，并返回应答给中转
4. wgtrf收到请求后，转发给client端
5. client端修改peer信息，从而实现p2p通讯

## 建议搭建HeadScale也可以实现p2p功能
